### ISSUE TITLE
Stuck on Joining Multiplayer and Singleplayer Maps, Unstock on Death & Respawn

### ISSUE THREAD

**Issue by Schroedinger85** [ClaudiusMinimus/Create_Potato_Forge#15]
Description of the Bug:
Player gets stuck after join world (Single Player and Multiplayer), after dying by command and respawning, player is not stuck anymore.
Issue started on 7th January 2023 arround 2pm (UTC+1) when ExtraStorage received an update.
Other Side affects that may be connected to it:
sleeping won't trigger they animation for lying down, you just stand on the bed, night will go over still.
addtional inventarbar can't shown (Rings/back etc)

Reproducing the Bug
Join any world, even new single player worlds have the issue

Expected behavior
Player should be able to move without dying

 - Minecraft Version 1.18.1
 - Pack Version2.6.0
 - Have you added any additional mods: n

Additional context
Tested it individuelly on 2 PCs, restartet the Server, we can not use a higher Version like 2.7.1 because we do not have a server version for this. IT seems to fail with ExtraStorage sinc this is the only Error that also is present with Single Player and Both Clients in Multiplayer

**Logs and Crash Reports**
[15:55:18] [Forge Version Check/INFO]: [extrastorage] Starting version check at https://raw.githubusercontent.com/Edivad99/mod-version-controll/master/extrastorage_update.json
[15:55:18] [Forge Version Check/WARN]: Failed to process update information
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 31 column 10 path $..2.2.1
	at com.google.gson.Gson.fromJson(Gson.java:947) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.8.jar%2322!:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:189) ~[fmlcore-1.18.1-39.0.14.jar%23143!:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:128) [fmlcore-1.18.1-39.0.14.jar%23143!:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 31 column 10 path $..2.2.1
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:490) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:69) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!:?]
	... 6 more
[15:55:18] [Forge Version Check/WARN]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.Gson.fromJson(Gson.java:944) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.8.jar%2322!:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:189) ~[fmlcore-1.18.1-39.0.14.jar%23143!:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:128) [fmlcore-1.18.1-39.0.14.jar%23143!:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!:?]
	... 6 more
[latest.log](https://github.com/ClaudiusMinimus/Create_Potato_Forge/files/10366828/latest.log)

**Comment by Schroedinger85** [comment]
It seems issue is a bit older, just odd it occured randomly for us.
Solution:
For player, just set versionCheck = false in \minecraft\config\fml.toml.
For package makers, upgrading to ExtraStorage-1.18.2-2.2.0 should fix the problem. 

Checked and can confirm it works. (the player solution at least)

See also:
https://github.com/benbenlaw/skyopolis-5/issues/22

**Comment by ClaudiusMinimus** [comment]
I need to get working on the transition to 1.19.2. I'll try to get a 1.18.2 server files made this week and then 1.19.2. Thank you for reporting this.

**Comment by ClaudiusMinimus** [comment]
The pack has been updated to 1.19.2. Here are some upgrade [instructions](https://github.com/ClaudiusMinimus/Create_Potato_Forge/blob/main/docs/upgrade_info.md)

**Comment by Schroedinger85** [comment]
Thanks, Migration was successfully completed.

Best Regards

Am Do., 19. Jan. 2023 um 21:10 Uhr schrieb ClaudiusMinimus <
***@***.***>:
